# Generated by Django 2.1.5 on 2019-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190604_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
